language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
script:
  - npm run lint
  # - npm test
services: mongodb
env: MONGODB_URI=mongodb://localhost:27017/travis APP_SECRET=somereallygoodsecretreallyreallygood
